# Generated by Django 4.2.2 on 2023-06-26 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='pw_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
