# Generated by Django 4.2 on 2023-05-31 10:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_users_otp"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="otp",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
