# Generated by Django 4.2 on 2023-06-03 19:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_users_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_otp_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="is_superuser",
            field=models.BooleanField(default=True),
        ),
    ]
